-- AlterTable
ALTER TABLE "Property" ALTER COLUMN "bedrooms" SET DATA TYPE TEXT,
ALTER COLUMN "bathrooms" SET DATA TYPE TEXT,
ALTER COLUMN "toilets" SET DATA TYPE TEXT,
ALTER COLUMN "parking_spaces" SET DATA TYPE TEXT;
