import {
  Furnishing,
  ListingType,
  PropertyStatus,
  PropertyType,
  UserRole,
} from '@prisma/client';
import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Buyer User',
      email: 'buyer@example.com',
      password_hash: bcrypt.hashSync('123456'),
      role: 'buyer' as UserRole,
      phone_number: '09128734756',
    },
    {
      name: 'Agent User',
      email: 'agent@example.com',
      password_hash: bcrypt.hashSync('123456'),
      role: 'agent' as UserRole,
      profile_picture: 'https://github.com/shadcn.png',
      phone_number: '09128734756',
    },
    {
      name: 'Agent User2',
      email: 'agent2@example.com',
      password_hash: bcrypt.hashSync('123456'),
      role: 'agent' as UserRole,
      profile_picture: 'https://github.com/shadcn.png',
      phone_number: '091287837656',
    },
    {
      name: 'Admin User',
      email: 'admin@example.com',
      password_hash: bcrypt.hashSync('123456'),
      role: 'admin' as UserRole,
      phone_number: '09128734756',
    },
  ],
  properties: [
    {
      // id: '680865758756596',
      // agentId: '39f36cb6-0fcc-4c88-afa7-eed65bc3a5c0', // ✅ Correct FK scalar
      title: '5 Bedroom Duplex For Sale',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam quis quam et consequat. Donec risus velit, vestibulum at dapibus sed, rhoncus sit amet ligula. Cras accumsan ante finibus diam fringilla, nec ultricies ex semper. Cras imperdiet tortor in consequat facilisis. Aliquam eleifend gravida urna eu porttitor. Mauris augue ante, euismod ac ullamcorper et, interdum a neque. Vestibulum augue felis, malesuada ut eleifend a, pharetra vitae massa. Aenean scelerisque id ipsum non faucibus. Integer id metus nec eros sollicitudin rhoncus vel et velit. Proin sagittis eleifend ipsum, nec iaculis dolor laoreet elementum. Donec ante velit, mattis quis turpis ut, maximus vestibulum nibh. Nam volutpat rutrum nibh, vel finibus tortor auctor non. Donec a volutpat ipsum. Proin ullamcorper tellus felis, nec fermentum augue auctor id. Pellentesque ac molestie enim, eget feugiat ipsum.',
      bedrooms: '5',
      bathrooms: '5',
      toilets: '6',
      parking_spaces: '5',
      size_sqm: 795.97,
      price: 1000000000.0,
      property_type: 'detached' as PropertyType,
      listing_type: 'sale' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'available' as PropertyStatus,
      street: 'Joel Ogunaike',
      city: 'Ikeja',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
    {
      // id: '680865753756596',
      // agentId: '39f36cb6-0fcc-4c88-afa7-eed65bc3a5c0', // ✅ Correct FK scalar
      title: '3 Bedroom Apartment For Sale',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam quis quam et consequat. Donec risus velit, vestibulum at dapibus sed, rhoncus sit amet ligula. Cras accumsan ante finibus diam fringilla, nec ultricies ex semper. Cras imperdiet tortor in consequat facilisis. Aliquam eleifend gravida urna eu porttitor. Mauris augue ante, euismod ac ullamcorper et, interdum a neque. Vestibulum augue felis, malesuada ut eleifend a, pharetra vitae massa. Aenean scelerisque id ipsum non faucibus. Integer id metus nec eros sollicitudin rhoncus vel et velit. Proin sagittis eleifend ipsum, nec iaculis dolor laoreet elementum. Donec ante velit, mattis quis turpis ut, maximus vestibulum nibh. Nam volutpat rutrum nibh, vel finibus tortor auctor non. Donec a volutpat ipsum. Proin ullamcorper tellus felis, nec fermentum augue auctor id. Pellentesque ac molestie enim, eget feugiat ipsum.',
      bedrooms: '3',
      bathrooms: '3',
      toilets: '4',
      parking_spaces: '5',
      size_sqm: 495.97,
      price: 200000000.0,
      property_type: 'apartment' as PropertyType,
      listing_type: 'sale' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'available' as PropertyStatus,
      street: 'Saka Jojo',
      city: 'Victoria Island',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
    {
      title: 'Luxury 3 Bedroom Apartment in Victoria Island',
      description:
        'Stunning modern apartment with panoramic views of Lagos. Features open-plan living, gourmet kitchen, and premium finishes throughout. The building offers 24/7 security, gym, and swimming pool.',
      bedrooms: '2',
      bathrooms: '3',
      toilets: '3',
      parking_spaces: '5',
      size_sqm: 495.97,
      price: 150000000.0,
      property_type: 'apartment' as PropertyType,
      listing_type: 'sale' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'available' as PropertyStatus,
      street: 'Muri Okunola',
      city: 'Victoria Island',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
    {
      title: '5-Bedroom Detached Duplex in Lekki',
      description:
        'Spacious family home in a secure estate. Features include a large garden, staff quarters, and ample parking space. Close to international schools and shopping centers.',
      bedrooms: '5',
      bathrooms: '4',
      toilets: '6',
      parking_spaces: '5',
      size_sqm: 850.5,
      price: 350000000.0,
      property_type: 'detached' as PropertyType,
      listing_type: 'sale' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'sold' as PropertyStatus,
      street: 'Admiralty Way',
      city: 'Lekki',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
    {
      title: 'Modern 2-Bedroom Flat for Rent in Ikoyi',
      description:
        'Elegant apartment in a prime location. Features include smart home system, concierge service, and shared recreational facilities. Perfect for young professionals.',
      bedrooms: '2',
      bathrooms: '2',
      toilets: '2',
      parking_spaces: '5',
      size_sqm: 320.25,
      price: 8000000.0,
      property_type: 'apartment' as PropertyType,
      listing_type: 'rent' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'unavailable' as PropertyStatus,
      street: 'Glover Road',
      city: 'Ikoyi',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
      tenancy_info:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam quis quam et consequat. Donec risus velit, vestibulum at dapibus sed, rhoncus sit amet ligula. Cras accumsan ante finibus diam fringilla, nec ultricies ex semper. Cras imperdiet tortor in consequat facilisis. Aliquam eleifend gravida urna eu porttitor. Mauris augue ante, euismod ac ullamcorper et, interdum a neque. Vestibulum augue felis, malesuada ut eleifend a, pharetra vitae massa. Aenean scelerisque id ipsum non faucibus. Integer id metus nec eros sollicitudin rhoncus vel et velit. Proin sagittis eleifend ipsum, nec iaculis dolor laoreet elementum. Donec ante velit, mattis quis turpis ut, maximus vestibulum nibh. Nam volutpat rutrum nibh, vel finibus tortor auctor non.',

      service_charge: '1000000',
      min_tenancy: '1 year',
      deposit: 1000000,
    },
    {
      title: '5 Bedroom House for Sale in Banana Island',
      description:
        'Premium office space in Lagos most exclusive neighborhood. High ceilings, natural light, and fiber internet ready. Includes access to business lounge and meeting rooms.',
      bedrooms: '5',
      bathrooms: '5',
      toilets: '6',
      parking_spaces: '5',
      size_sqm: 1200.0,
      price: 150000000.0,
      property_type: 'terrace' as PropertyType,
      listing_type: 'sale' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'available' as PropertyStatus,
      street: 'Banana Island',
      city: 'Ikoyi',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
    {
      title: '3-Bedroom Terrace House in GRA',
      description:
        'Charming renovated home with original architectural details. Features private garden, modern kitchen, and dedicated parking. Located in a quiet, tree-lined street.',
      bedrooms: '3',
      bathrooms: '2',
      toilets: '3',
      parking_spaces: '5',
      size_sqm: 420.75,
      price: 180000000.0,
      property_type: 'terrace' as PropertyType,
      listing_type: 'sale' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'available' as PropertyStatus,
      street: 'Eleke Crescent',
      city: 'GRA',
      state: 'Ikeja',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
    {
      title: 'Luxury Shortlet Apartment in Eko Atlantic',
      description:
        'High-end serviced apartment with daily cleaning. Features floor-to-ceiling windows, smart home technology, and access to private beach club. Minimum 3-night stay.',
      bedrooms: '2',
      bathrooms: '2',
      toilets: '2',
      parking_spaces: '5',
      size_sqm: 380.0,
      price: 250000.0,
      property_type: 'apartment' as PropertyType,
      listing_type: 'shortlet' as ListingType,
      furnishing: 'furnished' as Furnishing,
      status: 'available' as PropertyStatus,
      street: 'Eko Boulevard',
      city: 'Eko Atlantic',
      state: 'Lagos',
      images: [
        'https://res.cloudinary.com/domz2drcf/image/upload/v1750331906/properties/gl2iag3sja2wbvwyltg5.jpg',
      ],
    },
  ],
};

export default data;
